# <font color='Green'>Vorgehen bei einem <u>`ML-Datensatz`</u> </font>

`Schritt 1.` Data Loading and Preprocessing (Datenladen und Vorverarbeitung)

`Schritt 2.` Exploratory Data Analysis (Explorative Datenanalyse)

`Schritt 3.` Feature Engineering (Merkmalsentwicklung)

`Schritt 4.` Model Development(Modellentwicklung), Training & Evaluation

`Schritt 5.`  Forecasting (Prognosen)

### `Schitt 1:` Data Loading and Preprocessing (Datenladen und Vorverarbeitung)

In [28]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Einlesen vom Titanic-Datensatz
#  Der Datensatz ist gegeben in https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
# Laden eines Beispiel-Datensatzes
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
# Alternatieve:
df_2 = sns.load_dataset('titanic')
df_2.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

`Es fehlen Daten` z.B. bei Age welche wir brauchen denn,

Wir nehmen die Spalten: `Survived (Zielvariable), Age & Fare` 

und ersetzen die fehlenden Werte mit dem `Median` von Spalte `Age`

In [4]:
# Anzahl fehlender Werte in Age
df['Age'].isnull().sum()

np.int64(177)

In [5]:
# Ersetzen der fehlenden Werte in Age durch Median
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'].isnull().sum()

np.int64(0)

In [6]:
df_new =  df[['Survived', 'Age', 'Fare']]
df_new.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

### `Schritt 2:` Exploratory Data Analysis (Explorative Datenanalyse)

In [7]:
# 2.1 Grundlegende Informationen über den DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [8]:
# 2.2 Statistische Zusammenfassung der numerischen Spalten
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.361582    0.523008   
std     257.353842    0.486592    0.836071   13.019697    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [9]:
# 2.3 Überprüfung auf fehlende Werte
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


### `Schritt 3:` Feature Engineering (Merkmalsentwicklung)

### `Schritt 4:`Model Development(Modellentwicklung), Training & Evaluation

Datenaufbereitung: Zuerst extrahierst du die Ziel- und Feature-Daten aus deinem DataFrame.

Datenaufteilung: Du teilst die Daten in Trainings- und Testdaten auf.

Modelltraining: Du erstellst das Modell und trainierst es mit den Trainingsdaten.

Bewertung: Du prüfst die Genauigkeit und den Erfolg des Modells anhand von Metriken wie der Konfusionsmatrix und dem 

Klassifikationsbericht.


In [68]:
# 4.1 Datenaufbereitung -> extrahieren von Ziel- und Feature-Daten aus DataFrame df
y = df['Survived']  # Zielvariable
X = df[['Age', 'Fare']]  # Feature-Variablen

In [69]:
# 4.2 Datenaufteilung -> 80% Trainings- & 20% Test-Daten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [70]:
# 4.3 Modell erstellen
model = LogisticRegression()

In [71]:
# 4.4 Modell Trainieren 
model.fit(X_train, y_train)

LogisticRegression()

In [72]:
# 4.5 Modell bewertung
model.coef_

array([[-0.01305696,  0.01417598]])

In [73]:
model.intercept_

array([-0.56975656])

### `Schritt 5:`  Forecasting (Prognosen)

In [74]:
# Vorhersage für test daten
y_pred = model.predict(X_test)


In [75]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6480446927374302

Das bedeutet das Modell hat `64%` der Vorhersagen korrekt getroffen 

In [76]:
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[100,   5],
       [ 58,  16]])

Was bedeutet das für die Modellbewertung?
```python
`True Negatives (TN)` = 100:
    Das Modell hat 100 Passagiere korrekt als nicht überlebt (0) klassifiziert

`False Positives (FP)` = 5:
    Das Modell hat 5 Passagiere fälschlicherweise als überlebt (1) klassifiziert
    obwohl sie tatsächlich nicht überlebt haben (0) 
    Diese Fehler nennen wir "False Positives" oder "Typ I Fehler"

`False Negatives (FN)` = 58:
    Das Modell hat 58 Passagiere fälschlicherweise als nicht überlebt (0) klassifiziert 
    obwohl sie tatsächlich überlebt haben (1)
    Diese Fehler nennt man "False Negatives" oder "Typ II Fehler"

`True Positives (TP)` = 16:
    Das Modell hat 16 Passagiere korrekt als überlebt (1) klassifiziert

In [77]:
# 5.1 Neue Daten zum testen des Models
test_passengers = 10
ages = np.random.randint(20, 81, size=test_passengers)  
fares = np.random.uniform(80, 130, size=test_passengers)
new_pass = pd.DataFrame({
    'Age': ages,
    'Fare': fares,
})
df_2 = pd.DataFrame(new_pass)
df_2

Age        Fare
0   37  121.847394
1   53   86.346530
2   28  127.322108
3   79  105.205755
4   45  115.448254
5   75   86.992489
6   75  112.145417
7   76  107.008474
8   40  122.936683
9   68  125.413708

In [78]:
# 5.2 Vorhersage für die neuen Passagiere
new_prediction = model.predict(new_pass)
new_prediction

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [79]:
# 5.3 detaillierte Ausgabe
for _ in new_prediction:
    print('survived')  if _ == 1 else print('sorry my dear')

survived
sorry my dear
survived
sorry my dear
survived
sorry my dear
survived
sorry my dear
survived
survived
